### ISSUE TITLE
Duplicated headers in DCB pin definition

### ISSUE THREAD

**Issue by ypsun-umd** [ZishuoYang/UT-Backplane-mapping#1]
When inspecting the `backplaneMapping_SEAMPins_trueType_v4.1.xlsm`, I noticed that there are 2 headers with the same name `SEAM pin` (one in cell `C5`, the other `K5`).

Please specify the meaning of each header.

**Comment by ZishuoYang** [comment]
Ah sorry about the confusion. C5 is source pin, and K5 is destination pin.
