### ISSUE TITLE
Parse Altium-exported netlist

### ISSUE THREAD

**Issue by ypsun-umd** [ZishuoYang/UT-Backplane-mapping#11]
So far we prefer `pCad` netlist, since it looks like a `lisp` program, which is very easy to parse. Tom was suggesting some alternative format, the name which I forget.

**Comment by ypsun-umd** [comment]
We discovered that we can leverage `pyparsing` library. The following snippet might be useful:

## File to be parsed:
```
(asciiHeader
  (asciiVersion 3 0)
  (fileUnits Mil)
)
```

## Code snippet
```python
import pyparsing as pp
parser = pp.nextedExpr()
parser.parseFile(<filename>)
```

**Comment by ZishuoYang** [comment]
Add PcadReader to pyUTM/io.py for reading `Pcad` format netlist

**Comment by ypsun-umd** [comment]
It seems that `v0.4` can do PT-side checking now. The remaining task is to do the DCB-sdie checking.

**Comment by ypsun-umd** [comment]
DCB-DCB parsing has been implemented.
