### ISSUE TITLE
Possible error for LV_{SOURCE, RETURN, SENSE}

### ISSUE THREAD

**Issue by ypsun-umd** [ZishuoYang/UT-Backplane-mapping#2]
I finally got a working script that can partially reconstruct your original `test_AltiumNetlist_PT.CSV`. However, I found the following issues regarding these `LV_*`.

For example, for Pigtail slot `0`, pin `A06`, my result would be:
`JP0_JPU0_P2_EAST_LV_RETURN,0,A06,,`
whereas yours is:
`JP0_JPU0_P2_EAST_LV_RETURN,,,,`

Upon inspecting your script, I found the following snippet:
```python
elif ('LV_SOURCE' in net[6]):
    replaced = False
    for a in range(0,len(list_BOB)):
        if list_BOB[a]=='GND' or list_BOB[a]=='': continue
        if ( ('JP'+net[3]) in list_BOB[a].split('_') ) and ( net[6] in list_BOB[a] ) :
            print(list_BOB[a] + ',' +net[3]+','+net[4]+net[5]+','+''+','+'')
            replaced=True
    if replaced==False:
        print('JP'+net[3]+net[4]+net[5]+'_ForRefOnly_'+net[6]+ ',' +net[3]+','+net[4]+net[5]+','+''+','+'')
```
which led me to believe that mine is the correct behavior.

**Comment by ZishuoYang** [comment]
Yes, the reference pin should be printed. Unknown bug in `reformat_for_Altium.py` caused this to happen, but this is no longer a problem in `ypsun-umd`'s major rewrite.
