### ISSUE TITLE
Possible problem: no parenthesis after "or"

### ISSUE THREAD

**Issue by ypsun-umd** [ZishuoYang/UT-Backplane-mapping#29]
In the latest commit:
```python
...for pt_id in range(0, len(pt_descr)):
    for pt_entry in pt_descr[pt_id]:
        if pt_entry['Signal ID'] is not None \
                and (pt_entry['Signal ID'].endswith('SCL_N') or
                     pt_entry['Signal ID'].endswith('SDA_N') or
                     pt_entry['Signal ID'].endswith('RESET_N')):
```
There is no parenthesis after the second `and`. These `or`s might not be behave as intended.

**Comment by ypsun-umd** [comment]
On a second thought, that snippet seems to be correct, since `and` binds tighter than `or`, once the first 2 conditions are satisfied, `Python` would give you `True`.

Still, I'd like to confirm that this is the intended behavior.

**Comment by ZishuoYang** [comment]
Yes, the intended behaviors is to return `True` when any of the three OR conditions is `True`
