### ISSUE TITLE
Auxiliary list for depopulated signals and more

### ISSUE THREAD

**Issue by yipengsun** [ZishuoYang/UT-Backplane-mapping#37]
@ZishuoYang we talked about this with Tom yesterday, but I forgot the details, could you define what we need to do here?

Also about how to treat differential pairs and other stuffs.

**Comment by ZishuoYang** [comment]
There are 3 types of signals that need to be listed per PT connector: 

1. Depopulated `ELK`, `EC_RESET`, `HYB_i2C`, `DC_OUT_RCLK`, `MC_TFC`

2. All `LV_SENSE_GND`

3. All `EC_RESET`, `EC_HYB_i2C`
