### ISSUE TITLE
Inconsistencies between copy-paste list and implemented netlist

### ISSUE THREAD

**Issue by yipengsun** [ZishuoYang/UT-Backplane-mapping#73]
Some additional inconsistencies:

- [x] **CP**: `JP0_FRO_P3_LV_SENSE_GND`, **implemented**: `JP4F05_P2_EAST_LV_SENSE_GND`, and other 54 `LV_SENSE_GND` entries.
- [x] **CP**: `JP8_JPU2_P4_LV_RETURN`, **implemented**: `JP8_JPL2_P4_LV_RETURN` (only 1).
- [x] **CP**: `*OUT*`, `JDX_B1`, `JDX_B3`, **implemented**: None

**Comment by yipengsun** [comment]
For the `LV_RETURN` part, so far it seems that we just need to update the breakout board specification file.

**Comment by yipengsun** [comment]
The `OUT`, `B1`, and `B3` are unused outputs, and we don't need to do anything with them.

**Comment by ZishuoYang** [comment]
Regarding `JP8_JPL2_P4_LV_RETURN`, the implemented should be correct and our input yml file needs to be updated (change JPU2 to JPL2).
